expense_health_check:
    path: /api/v1/expenses/health-check
    controller: App\Context\Expense\Infrastructure\Http\Controller\HealthCheckController
    methods: ['GET']

expense_enter:
    path: /api/v1/expenses/enter
    controller: App\Context\Expense\Infrastructure\Http\Controller\ExpenseEnterPutController
    methods: ['PUT']

expense_compensate:
    path: /api/v1/expenses/compensate/{id}
    controller: App\Context\Expense\Infrastructure\Http\Controller\CompensateExpensePatchController
    methods: ['PATCH']

expense_update:
    path: /api/v1/expenses/update/{id}
    controller: App\Context\Expense\Infrastructure\Http\Controller\UpdateExpensePatchController
    methods: ['PATCH']

expense_payed:
    path: /api/v1/expenses/payed/{id}
    controller: App\Context\Expense\Infrastructure\Http\Controller\ExpensePayedPatchController
    methods: ['PATCH']

expenses_get:
    path: /api/v1/expenses
    controller: App\Context\Expense\Infrastructure\Http\Controller\GetAllExpensesController
    methods: ['GET']

expense_get:
    path: /api/v1/expenses/{id}
    controller: App\Context\Expense\Infrastructure\Http\Controller\GetExpenseByIdController
    methods: ['GET']