doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            # Mapeo por contexto (Vertical Slice)
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Context/User/Domain/Entity'
                prefix: 'App\Context\User\Domain\Entity'
                alias: User
            
            Product:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Context/Account/Domain/Entity'
                prefix: 'App\Context\Account\Domain\Entity'
                alias: Account
            
            # Entidades compartidas (si las tienes)
            Shared:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Shared/Domain/Entity'
                prefix: 'App\Shared\Domain\Entity'
                alias: Shared

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
