framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        # This part is important - make sure queries are handled synchronously
        transports:
            sync: 'sync://'

        routing:
            'App\Shared\Application\Query': sync
