<?php

namespace App\Tests\Context\Account\Domain;

use App\Context\Account\Domain\AccountCode;
use App\Tests\Shared\Domain\MotherCreator;
use App\Tests\Shared\Domain\WordMother;

class AccountCodeMother
{
    public static function create(?string $value = null): AccountCode
    {
        $autogenerated = MotherCreator::random()->regexify('[A-Z0-9]{8}');
        return  new AccountCode($value ?? $autogenerated);
    }
}