imports:
    - { resource: services.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Add this section to alias the repository interface to your in-memory implementation
    App\Context\EventStore\Domain\StoredEventRepository:
        class: App\Tests\Context\Shared\Infrastructure\Persistence\InMemoryStoredEventRepository

    # Ensure the service is public so we can fetch it in tests
    App\Tests\Context\Shared\Infrastructure\Persistence\InMemoryStoredEventRepository:
        public: true
