gas_price_calculate:
    path: /api/v1/gas/price
    controller: App\Context\Gas\Infrastructure\Http\Controller\CalculateGasPricePutController
    methods: ['PUT']

gas_reading_record:
    path: /api/v1/gas/reading
    controller: App\Context\Gas\Infrastructure\Http\Controller\RecordGasReadingPutController
    methods: ['PUT']

gas_price:
    path: /api/v1/gas/price
    controller: App\Context\Gas\Infrastructure\Http\Controller\FindGasPriceController
    methods: [GET]

get_last_gas_reading:
  path: /api/v1/gas/resident-units/{id}/last-reading
  controller: App\Context\Gas\Infrastructure\Http\Controller\FindLastGasReadingController
  methods: [GET]
