gas_price_calculate:
    path: /api/v1/gas/price
    controller: App\Context\Gas\Infrastructure\Http\Controller\CalculateGasPricePutController
    methods: ['PUT']

gas_reading_record:
    path: /api/v1/gas/reading
    controller: App\Context\Gas\Infrastructure\Http\Controller\RecordGasReadingPutController
    methods: ['PUT']

gas_price:
    path: /api/v1/gas/price
    controller: App\Context\Gas\Infrastructure\Http\Controller\FindGasPriceController
    methods: [GET]

get_gas_reading_by_period:
    path: /api/v1/gas/resident-units/{id}/reading/{year}/{month}
    controller: App\Context\Gas\Infrastructure\Http\Controller\FindGasReadingController
    methods: [GET]

gas_get_average_consumption:
    path: /api/v1/gas/resident-units/{id}/average-consumption
    controller: App\Context\Gas\Infrastructure\Http\Controller\GetAverageGasConsumptionController
    methods: ['GET']